IF NOT DEFINED DFS SET DFS=NON
SET DATASERVERNAME=dataserver-a
IF %DFS% EQU OUI SET DATASERVERNAME=TaggInfo.fr
SET SOURCESERVERNAME=sourceserver-a
IF %DFS% EQU OUI SET SOURCESERVERNAME=TAGGSRVSRC01

SET FILESERVERNAME=FileServer_a
SET SOFTSERVERNAME=SOFTSERVER-A
SET TRANSFERTSERVERNAME=Stsp-a
SET FILETRANSFERTSERVER=ftpserver-a
SET NEWFILETRANSFERTSERVER=TAGGSRVSTFILE01
SET SERVER_DATA=\\%DATASERVERNAME%\Clients
SET SERVER_DATA_BUSKRO=\\%DATASERVERNAME%\Buskro
SET SERVER_SOURCE=\\%SOURCESERVERNAME%\Clients
SET SERVER_SOURCE_BUSKRO=\\%SOURCESERVERNAME%\Buskro
SET SERVER_DEV1=\\%FILESERVERNAME%\Development
SET SERVER_DEV2=\\%SOFTSERVERNAME%\Development
SET SERVER_PROG=\\%SOFTSERVERNAME%\Programmation
SET SERVER_TRANSFERT=\\%TRANSFERTSERVERNAME%\data_stserver
SET SERVER_NEW_TRANSFERT=\\%NEWFILETRANSFERTSERVER%\ClientsTAGG
SET SERVER_FTP=\\%FILETRANSFERTSERVER%\FtpVirtuel

SET LECTEUR_SERVEUR_DATA=U:
IF %DFS% EQU OUI SET LECTEUR_SERVEUR_DATA=Y:
SET LECTEUR_SERVEUR_SOURCE=V:
IF %DFS% EQU OUI SET LECTEUR_SERVEUR_SOURCE=Z:

SET LECTEUR_SERVEUR_ROUTAGE=D:
