
rem=========================================================================== 
rem  Forcage des programmes par défaut
rem===========================================================================
IF NOT DEFINED TYPE_TRAIT SET TYPE_TRAIT=REPETITIF

SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION%
SET EXTRACTTEXTPDF=%EXTRACTTEXTPDF_CHEMIN_TEST%
SET TECHROUTINGC=%TECHROUTINGC_CHEMIN_TEST%
SET PDFRIP=%PDFRIP_CHEMIN%
SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%



rem ====================================FORCAGE PRODINFO=============================================================

IF %DFS% EQU OUI SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
IF %DFS% EQU OUI SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
SET PRODINFOC=%PRODINFOC_CHEMIN_TEST_VALIDATION%
SET PRODINFOC_ETAPE=%PRODINFOC_CHEMIN_TEST_VALIDATION%

REM IF "%TRAITEMENT_16H%" EQU "VRAI" SET PRODINFOC=\\dc2_a\toutlemonde\Simon\ProdInfoC\Release\ProdInformationC.exe

REM ===================================================================
REM                 FORCAGE DOSSIER TEST R&D
REM ===================================================================
IF %NUMCMD% EQU 40829 SET TECHROUTINGC=%TECHROUTINGC_CHEMIN_BASE_TEST%
IF %NUMCMD% EQU 40829 SET SORTEXEC=%SORTEXEC_CHEMIN_BASE_TEST%

REM ===================================================================
REM                 FORCAGE PDFRIP
REM ===================================================================

REM ===================================================================
REM                 FORCAGE EDITIONC
REM ===================================================================

IF /I "%TYPE_TRAIT%" EQU "PONCTUEL" SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%

::EDEDOC
IF %NUMCMD% EQU 72805 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
::MASSIFICATION
IF %NUMCMD% EQU 75470 SET EDITIONC=%EDITIONC_CHEMIN_TEST%
::AMUNDI
rem IF %MODE% NEQ PROD IF %NUMCMD% EQU 71191 SET EDITIONC=%EDITIONC_CHEMIN_TEST%

::BAYARD
IF %NUMCMD% EQU 77579 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%

::DIFF_PLUS
IF %NUMCMD% EQU 77586 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%

::UNICEF
IF %NUMCMD% EQU 71938 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%

::SSTRN Publipstage
IF %NUMCMD% EQU 77760 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%

::APF
IF %NUMCMD% EQU 71547 SET EDITIONC=%EDITIONC_CHEMIN_TEST%
::SIDACTION
IF %NUMCMD% EQU 71942 SET EDITIONC=%EDITIONC_CHEMIN_TEST%
::UNICEF
IF %NUMCMD% EQU 71938 SET EDITIONC=%EDITIONC_CHEMIN_TEST%

::DEMANDE MELINA

IF %NUMCMD% EQU 68155 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71187 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71302 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71547 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71795 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71802 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71808 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71937 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 71938 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 72048 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 72805 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73017 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73039 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73168 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73170 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73270 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73292 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73395 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73627 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73691 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 73773 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 74190 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 74945 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75470 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75485 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75595 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75636 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75638 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75640 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75641 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75642 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 75740 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 76091 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 76326 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 76537 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 76558 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77457 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77482 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77580 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77581 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77583 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77589 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77604 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77620 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77716 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%
IF %NUMCMD% EQU 77909 SET EDITIONC=%EDITIONC_CHEMIN_PRODUCTION_TEST%

REM ===================================================================
REM                 FORCAGE AFPTLEINDEXER
REM ===================================================================
::DIFF+ SOCIETE GENERALE
IF %NUMCMD% EQU 76214 SET AFPTLEINDEXER=%AFPTLEINDEXER_CHEMIN_TEST%

REM ===================================================================
REM                 FORCAGE TECHROUTINGC
REM ===================================================================

::MONCEAU
IF %NUMCMD% EQU 74089 SET TECHROUTINGC=%TECHROUTINGC_CHEMIN_TEST%
::CIMUT MCEN
IF %NUMCMD% EQU 73301 SET TECHROUTINGC=%TECHROUTINGC_CHEMIN_TEST%
::EDEDOC
IF %NUMCMD% EQU 72805 SET TECHROUTINGC=%TECHROUTINGC_CHEMIN_TEST%
::NATIXIS OMEGA
IF %NUMCMD% EQU 76349 SET TECHROUTINGC=%TECHROUTINGC_GENERIQUE%
::VPC
IF %NUMCMD% EQU 77333 SET TECHROUTINGC=%TECHROUTINGC_CHEMIN_TEST%

REM ===================================================================
REM                 FORCAGE DISTILLER
REM ===================================================================
::CNP ANGERS
IF %NUMCMD% EQU 71795 IF EXIST "C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\acrodist.exe" SET DISTILLER="C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\acrodist.exe"

REM ===================================================================
REM                 FORCAGE EXTRACTTEXTPDF
REM ===================================================================
::REX ROTARY
IF %NUMCMD% EQU 73773 SET EXTRACTTEXTPDF=%EXTRACTTEXTPDF_CHEMIN_PROD%

REM ===================================================================
REM                 FORCAGE MERGEPDFFILES
REM ===================================================================
::REX ROTARY
IF %NUMCMD% EQU 73017 SET MERGEPDFFILES=%MERGEPDFFILES_TEST%

REM ===================================================================
REM                 FORCAGE RAPPRO
REM ===================================================================
::DIFF+ AFM
IF %NUMCMD% EQU 73627 SET RAPPRO=\\SOURCESERVER-A\Clients\DIFF_PLUS\AFM\COURRIER_GESTION\COURRIER_GESTION\Bibliotheques\Progs\Rapprochement.exe

REM ===================================================================
REM                 FORCAGE DATAMANAGERC
REM ===================================================================

IF %MODE% NEQ PROD SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
IF /I "%TYPE_TRAIT%" EQU "PONCTUEL" SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST% 

::AMUNDI ESR
IF %MODE% NEQ PROD IF %NUMCMD% EQU 71191 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::DIFF_PLUS
IF %NUMCMD% EQU 77472 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

rem obliger sinon ca bug sur le routing :    
IF %NUMCMD% EQU 77449 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
IF %NUMCMD% EQU 77482 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%
IF %NUMCMD% EQU 77448 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%

IF %NUMCMD% EQU 77594 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
rem IF %NUMCMD% EQU 77347 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%
IF %NUMCMD% EQU 77454 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
rem CIMUT appelCot
IF %NUMCMD% EQU 77347 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::TEST MILEE
IF %NUMCMD% EQU 77602 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::DIFF PLUS
rem IF %NUMCMD% EQU 77586 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Ededoc
IF %NUMCMD% EQU 72805 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::
::IF %NUMCMD% EQU 77748 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%

::FRC_NEURODON
IF %NUMCMD% EQU 77468 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::BANQUE POPULAIRE AURA
IF %NUMCMD% EQU 77570 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
IF %NUMCMD% EQU 77601 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA WILLIS ==> T0
IF %NUMCMD% EQU 77582 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::TEST EPIC
IF %NUMCMD% EQU 74100 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA BNP 
IF %NUMCMD% EQU 77577 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA RCF 
IF %NUMCMD% EQU 77729 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA CAVP ==> T0 
IF %NUMCMD% EQU 77605 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA VIVASON ==> I8 
IF %NUMCMD% EQU 77713 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

IF %NUMCMD% EQU 77580 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA MOULIN DE L'AUNAY
IF %NUMCMD% EQU 77578 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
    
::CIFEA NEUVILLE
IF %NUMCMD% EQU 77457 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CNOPP                                                 
IF %NUMCMD% EQU 77463 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::MAAF                                                  
IF %NUMCMD% EQU 77595 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA PULSE JAPAN                                                  
IF %NUMCMD% EQU 77453 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CIFEA PULSE JAPAN                                                  
IF %NUMCMD% EQU 77627 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Cardif T0                                                 
IF %NUMCMD% EQU 73801 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Etablissement Thermal
IF %NUMCMD% EQU 77715 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Cifea I8
IF %NUMCMD% EQU 77609 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Cifea VisionDuMonde
IF %NUMCMD% EQU 77736 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Financo T0
IF %NUMCMD% EQU 77732 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Cifea Trading_EL_RAFY_GOLD
IF %NUMCMD% EQU 77583 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Cifea CARREFOUR_BANQUE
IF %NUMCMD% EQU 77716 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::Cifea GADOL
IF %NUMCMD% EQU 77909 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::MGFI
IF %NUMCMD% EQU 77338 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::VPC G1-G4-G2B
IF %NUMCMD% EQU 77333 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST% 
IF %NUMCMD% EQU 77332 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
IF %NUMCMD% EQU 76896 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
IF %NUMCMD% EQU 73393 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
IF %NUMCMD% EQU 77747 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%

::CAMBIUM
IF %NUMCMD% EQU 73039 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%

::FRC NEURODON
IF %NUMCMD% EQU 77756 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST% 

::DE NEUVILLE 
IF %NUMCMD% EQU 77457 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST% 

::MICHELIN OLD
IF %NUMCMD% EQU 55954 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%
    
::NTT DATA SPAIN
rem IF %NUMCMD% EQU 76091 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%

::DIFF PLUS DOMING
IF %NUMCMD% EQU 75865 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%    

::cifea pulse
IF %NUMCMD% EQU 77874 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%    

::Pollinis 2023-2024
IF %NUMCMD% EQU 77739 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST% 

::CIFEA BNP KYC
IF %NUMCMD% EQU 77572 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%   

::CIFEA LA_BANQUE_POSTALE
IF %NUMCMD% EQU 78034 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%   

::CIFEA BEXLEY
IF %NUMCMD% EQU 77604 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%   

::CIFEA PG MALIN
IF %NUMCMD% EQU 77574 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%   

::BAYARD PELERIN
IF %NUMCMD% EQU 75640 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%   

::CIFEA LCL
IF %NUMCMD% EQU 78052 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%   

::CIFEA LCL NAMAD
IF %NUMCMD% EQU 77576 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_PROD%   

::CIFEA NEURODON REPETIFI UwU
IF %NUMCMD% EQU 78063 SET DATAMANAGERC=%DATAMANAGERC_CHEMIN_TEST%   

REM ===================================================================
REM                 FORCAGE PRODINFOC
REM ===================================================================



::NTT DATA SPAIN
IF %NUMCMD% EQU 76091 SET PRODINFOC=%PRODINFOC_CHEMIN_TEST_ALPHA%

::AMUNDI
IF %NUMCMD% EQU 71191 SET PRODINFOC=%PRODINFOC_CHEMIN_TEST_ALPHA%
rem IF %NUMCMD% EQU 71191 SET PRODINFOC=%PRODINFOC_CHEMIN_PROD%

::CATITRES
IF %NUMCMD% EQU 74685 SET PRODINFOC=%PRODINFOC_CHEMIN_TEST_ALPHA%
::QIS_PUBLIPOSTAGE
IF %NUMCMD% EQU 77330 SET PRODINFOC=%PRODINFOC_CHEMIN_PROD%

::UNICEF       
rem IF %NUMCMD% EQU 71938 SET PRODINFOC=%PRODINFOC_CHEMIN_PROD%
    
    
REM ===================================================================
REM                 FORCAGE CHEMIN_PROGS
REM ===================================================================
::MICHELIN OLD
IF %NUMCMD% EQU 55954 SET CHEMIN_PROGS=%CHEMIN_PROGS_SPECIFIQUE_DOSSIER%
::EDEDOC
IF %NUMCMD% EQU 72805 SET CHEMIN_PROGS=%CHEMIN_PROGS_SPECIFIQUE_DOSSIER%

REM ===================================================================
REM        Gestion des quantité de bascule pour le cluster
REM ===================================================================
SET BASCULE_CLUSTER=2000
::AMUNDI ESR JOURNALIER
IF %NUMCMD% EQU 71191 SET BASCULE_CLUSTER=1000
::CA TITRES JOURNALIER
IF %NUMCMD% EQU 74685 SET BASCULE_CLUSTER=1000
IF %NUMCMD% EQU 75639 SET BASCULE_CLUSTER=5000

REM ===================================================================
REM                     Gestion des options merge
REM ===================================================================
::FCI CDC
IF %NUMCMD% EQU 71647 SET SUPPLEMENT_MERGE=useNewBanNumerotation()

REM ===================================================================
REM             GESTION DES VARIABLES FORCE POUR COMMUN
REM ===================================================================

::MICHELIN OLD
IF %NUMCMD% EQU 55954 SET TRAIT_DECOUPELOT_AUTRES=%SILENT_COMMUNS% CALL %CHEMIN_COMMUNS_ROUTINES%\Lotissement\DecoupeLotAutres.bat

::DIFF+ SOCIETE GENERALE
IF %NUMCMD% EQU 76214 SET TRAIT_LOTS=%SILENT_COMMUNS%       CALL %CHEMIN_COMMUNS_ROUTINES%\Lotissement\Lots_SiloeV2.bat
IF %NUMCMD% EQU 76214 SET TRAIT_DECOUPELOT=%SILENT_COMMUNS% CALL %CHEMIN_COMMUNS_ROUTINES%\Lotissement\DecoupeLot_SiloeV2.bat
IF %NUMCMD% EQU 76214 SET TRAIT_LOTS=%SILENT_COMMUNS%       CALL %CHEMIN_COMMUNS_ROUTINES%\Lotissement\Lots_SiloeV2.bat
IF %NUMCMD% EQU 76214 SET TRAIT_SSLOTS=%SILENT_COMMUNS%     CALL %CHEMIN_COMMUNS_ROUTINES%\Lotissement\SSLots_SiloeV2.bat

REM ===================================================================
REM   Les deux lignes dessous servent à désactiver la déclaration des étapes dans ProdInfo.
REM ===================================================================

REM SET DECLARE_DEBUT_ETAPE=ECHO
REM SET DECLARE_DEBUT_SOUS_ETAPE=ECHO

rem IF BENOIT ALORS PAS DE DECLARATION ETAPE !!!!
rem Benoit n'aime pas les étapes grrr
if "%COMPUTERNAME%" EQU "PROGRA-13" SET DECLARE_DEBUT_ETAPE=ECHO
if "%COMPUTERNAME%" EQU "PROGRA-13" SET DECLARE_DEBUT_SOUS_ETAPE=ECHO

IF "%NUMCMD%" EQU "40491" (
    SET PRODINFOC=\\SOFTSERVER-A\Development\TagG-Informatique\ProductionInformation\ProdInformationsC\Database_a\AlphaPreProd\ProdInformationC.exe
    SET DATAMANAGERC=D:\Develops\Main\FileProcess\DataManager\Clients\DataManagerC\bin\x64\Debug\datamanagerc.exe
)

REM Toujour laisser ce code dessous à la fin !!!
IF "%DATAMANAGER_BENCHMARK_DISCONNECT%" EQU "1" (
    SET TAGGALEA=\\FileServer_a\Development\TagG-Informatique\ProductionFileProcessing\TaggAleaTest\TaggAlea.exe
    SET DATAMANAGERC=%DATAMANAGERC_DISCO%
    IF DEFINED PRODINFOC_DISCO SET PRODINFOC=%PRODINFOC_DISCO%
    SET MAIL_DM=;datamanager@Tagginfo.com
)
